[features]
seeds = false
[programs.localnet]
solana_twitter = "G2QLaNJt9aycxHURsJhqo89MjPp7peLKQyFjvvABwZQA"

[programs.devnet]
solana_twitter = "G2QLaNJt9aycxHURsJhqo89MjPp7peLKQyFjvvABwZQA"

[programs.mainnet]
solana_twitter = "G2QLaNJt9aycxHURsJhqo89MjPp7peLKQyFjvvABwZQA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/doms/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

